In [2]:
!pip3 install numpy


Defaulting to user installation because normal site-packages is not writeable


##Now  we start numpy


In [1]:
import numpy as np

In [6]:
arr=np.array([[1,2,3],#way of representing 2d array
            [4,5,6]])

In [7]:
type(arr)#printing the type of the array

numpy.ndarray

In [8]:
arr.ndim#printing the dimension of the array

2

In [9]:
arr.shape#printing the shape of the array rows and column

(2, 3)

In [11]:
arr1=np.array([1,23,3])#way of representing 1d array

In [12]:
arr1.shape

(3,)

In [13]:
arr.dtype#printing the type of element present in array

dtype('int32')

In [15]:
#creating array for list with type float
a=np.array([[1,2,3,4],[3,4,4,5]],dtype='float')
print("Array ceated using passed list: \n",a)

Array ceated using passed list: 
 [[1. 2. 3. 4.]
 [3. 4. 4. 5.]]


In [16]:
#creating array from tuple
b=np.array((1,2,3,4))
print("Array created using tuple: \n",b)

Array created using tuple: 
 [1 2 3 4]


In [18]:
#creating array of 3X4 with all zeros
c=np.zeros((3,4))
print("an array initialized with all zeroe:\n",c)

an array initialized with all zeroe:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
#create an array with random values
d=np.random.random((2,2))
print("Random array : \n",d)

Random array : 
 [[0.99700366 0.22940383]
 [0.85480422 0.68452872]]


In [24]:
#create a constant value array of complex type 
e=np.full((3,4),6,dtype='complex')
print("array initialized with all 6 .Array type is complex: \n ",e)

array initialized with all 6 .Array type is complex: 
  [[6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]]


In [26]:
#create a sequence of integers from 0 to 30 with steps of 5
f=np.arange(0,30,5)
print("sequential array with steps of 5: \n",f)

sequential array with steps of 5: 
 [ 0  5 10 15 20 25]


In [27]:
#create a sequence of 10 values in range 0 to 5
g=np.linspace(0,5,10)
print("a sequential array with 10 values b/w 0 and 5:\n",g)

a sequential array with 10 values b/w 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [28]:
np.ones((3,4))#all elements in the array 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.eye(3)#indentity matrix create 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
ar=np.array([[1,2,3,3],[2,2,2,2],[4,43,3,5]])
newarr=ar.reshape((4,3))
print("original array\n",ar)
print("Reshaped array\n",newarr)

original array
 [[ 1  2  3  3]
 [ 2  2  2  2]
 [ 4 43  3  5]]
Reshaped array
 [[ 1  2  3]
 [ 3  2  2]
 [ 2  2  4]
 [43  3  5]]


In [40]:
ar1=np.array([[1,2,3],[3,4,5]])
flarr=ar1.flatten()
print("\noriginal array:\n",ar1)
print("flattend array:\n",flarr)


original array:
 [[1 2 3]
 [3 4 5]]
flattend array:
 [1 2 3 3 4 5]


In [42]:
arr=np.array([[2,3,4,5],[2,3,4,4],[4,5,5,6],[4,5,6,7]])



In [52]:
arr[0:1:1,0:1:1]

array([[2]])

In [61]:
a=np.array([1,2,3,4])


In [62]:
a+1#adding  1 on every element

array([2, 3, 4, 5])

In [63]:
a-3#subtracting 3 from each element

array([-2, -1,  0,  1])

In [64]:
a*10#multiplying each element by 10

array([10, 20, 30, 40])

In [65]:
a**2#squaring each element

array([ 1,  4,  9, 16])

In [68]:
a*2#doubled each element

array([10, 12, 14, 16])

In [77]:
a=np.array([[1,2,3,4],[4,5,6,7]])
b=np.array([[2,3,4,5],[2,3,4,1]])

In [78]:
a*b

array([[ 2,  6, 12, 20],
       [ 8, 15, 24,  7]])

In [79]:
a+b

array([[ 3,  5,  7,  9],
       [ 6,  8, 10,  8]])

In [80]:
a*b

array([[ 2,  6, 12, 20],
       [ 8, 15, 24,  7]])

In [81]:
a.dot(b)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [82]:
#create an array of sine values
a=np.array([0,np.pi/2,np.pi])
print("sine values of array elements: ",np.sin(a))

sine values of array elements:  [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [83]:
#exponential values
a=np.array([0,1,2,3])
print("exponent of array elements: ",np.exp(a))

exponent of array elements:  [ 1.          2.71828183  7.3890561  20.08553692]


In [84]:
#square root of array values
print("square root of array elements: ",np.sqrt(a))

square root of array elements:  [0.         1.         1.41421356 1.73205081]


In [87]:
#sort array
b=np.array([1,23,4,5])
print("Array elements in sorted order:\n",np.sort(b,axis=None))

Array elements in sorted order:
 [ 1  4  5 23]


In [89]:
#sort array row wise
a=np.array([[1,2,4,3,2],[2,1,3,2,3]])
print("row wise sorted array",np.sort(a,axis=1))

row wise sorted array [[1 2 2 3 4]
 [1 2 2 3 3]]


In [91]:
#specify sort algorithm
print("column wise sort by applying range-sort:\n",np.sort(a,axis=0,kind='mergesort'))

column wise sort by applying range-sort:
 [[1 1 3 2 2]
 [2 2 4 3 3]]


##stacking and splitting

In [93]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [94]:
#vertical stacking
print("vertical stacking\n",np.vstack((a,b)))

vertical stacking
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [95]:
#horizontal stacking
print("horizontal stacking:\n",np.hstack((a,b)))

horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [97]:
#stacking columns
print("column stacking\n",np.column_stack((a,b)))

column stacking
 [[1 2 5 6]
 [3 4 7 8]]


In [99]:
#concatentaion method
print("concatenating to 2nd axis:\n",np.concatenate((a,b),1))

concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


In [101]:
#horizontal spliting
print("spliting along horizontal axis into 2 parts\n",np.hsplit(a,2))

spliting along horizontal axis into 2 parts
 [array([[1],
       [3]]), array([[2],
       [4]])]


In [102]:
#vertical spliting
print("spliting along vertical axis into 2 parts\n",np.vsplit(a,2))

spliting along vertical axis into 2 parts
 [array([[1, 2]]), array([[3, 4]])]


In [104]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(np.min(a))#find min value in the array

0


In [105]:
#specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[1 2 2 0]
[1 0]


In [108]:
b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [110]:
c=np.array([1,5,4,2,0])
print(np.median(c))

#mean vs average is weighted
print(np.mean(c))
#weights
w=np.array([1,1,1,1,1])
print(np.average(c,weights=w))
#weighted mean=> n1*w1 +n2*w2/n1+n2
#standard deviation
u=np.mean(c)
mystd=np.sqrt(np.mean(abc(c-u)**2))
print(mystd)

2.0
2.4
2.4


NameError: name 'abc' is not defined